### ISSUE TITLE
Dogstatsd aggregator is complaining about empty values

### ISSUE THREAD

**Issue by AndreBremer** [DataDog/uwsgi-dogstatsd#4]
I am seeing lots of these in the dogstatsd log. 

```
2015-01-14 23:13:40 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:306) | Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 294, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 512, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 442, in parse_metric_packet
    raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
Exception: Metric value must be a number: myapp.worker.core.offloaded_requests, 
```

```uwsgi --connect-and-read``` shows data (although lots 0 values)

Suggestions?

**Comment by bjarocki** [comment]
Hello @AndreBremer, would you mind sending some information about the system which runs uwsgi?
ldd `which uwsgi`
or 
otool -L `which uwsgi` # in case of osx

**Comment by AndreBremer** [comment]
Sure thing!

uWSGI 2.0.9
```
	linux-vdso.so.1 =>  (0x00007fff012e8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f10b7215000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f10b6f0f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f10b6d0a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f10b6af1000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f10b678b000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f10b6223000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f10b5e5d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f10b743d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f10b5c3b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f10b5a37000)
```

**Comment by bjarocki** [comment]
@AndreBremer looks like 46c7d5f25e3b86c6fe00aaa4f24064d3abe5640c should fix the bug. Would you mind pulling master and confirm before I close the issue?

**Comment by AndreBremer** [comment]
Looking great! Thanks for the quick response and fix.
